BUPT-GAMMA/OpenHGNN

docs/source/api/model.rst
docs/source/api/openhgnn.models.rst
openhgnn/models/MHNF.py

用于生成在线文档，不过加入统一输入维度后，训练的epoch总在第二个epoch 报错，这个bug我没找到原因。

online word and modify model

---

docs/source/install/index.rst
docs/source/install/usage.rst

There are still two TODOs left.  If we don't have the list of datasets and tasks then we can remove them (though I would recommend putting together a list for them).

Edits to the get started document

---

.gitignore
README.md
main.py
openhgnn/models/HAN.py
openhgnn/models/base_model.py
openhgnn/trainerflow/node_classification.py

fix some potential problems of `README.md`;

add a visualization demo based on model  `HAN`;

---

openhgnn/dataset/LinkPredictionDataset.py

Sorry!This time I just have one commit.

fix a bug in LinkPredictionDataset

---

openhgnn/config.ini
openhgnn/models/DMGI.py
openhgnn/models/HGAT.py
openhgnn/trainerflow/node_classification.py
openhgnn/utils/sampler.py

Update models to support the test.
- [] All changes have test coverage

[Model]Update model

---

.readthedocs.yaml
README.md
README_EN.md
docs/source/get_started/index.rst
docs/source/locales/zh_CN/LC_MESSAGES/install.po
setup.py

[Fix] py3.6 version

---

openhgnn/config.ini
openhgnn/config.py
openhgnn/dataset/__init__.py
openhgnn/models/HGSL.py
openhgnn/utils/best_config.py

HGSL model fixed

---

openhgnn/dataset/__init__.py
openhgnn/dataset/alircd_dataset.py
tests/dataset/test_industrial_dataset.py

Integrate Alibaba Risk Commodity Detection Dataset

[Dataset] Alibaba Risk Commodity Detection Dataset

---

openhgnn/config.ini
openhgnn/config.py
openhgnn/dataset/EdgeClassificationDataset.py
openhgnn/dataset/__init__.py
openhgnn/dataset/mg2vec_dataset.py
openhgnn/experiment.py
openhgnn/models/Mg2vec.py
openhgnn/models/__init__.py
openhgnn/output/Mg2vec/README.md
openhgnn/sampler/mg2vec_sampler.py
openhgnn/tasks/__init__.py
openhgnn/tasks/edge_classification.py
openhgnn/trainerflow/__init__.py
openhgnn/trainerflow/mg2vec_trainer.py
openhgnn/utils/evaluator.py

Add the Mg2vec Model and add the EdgeClassification Task

[Model]Mg2vec

---

openhgnn/config.ini
openhgnn/config.py
openhgnn/trainerflow/link_prediction.py
openhgnn/trainerflow/node_classification.py
openhgnn/utils/sampler.py

[RGCN]: Add the ’fanout‘ attribute to configuration file to fix: "AttributeError: 'Config' object has no attribute 'fanout'" problem. The value of  ’fanout‘ is set to -1 by default and will need to be changed in the future based on the model parameters.
[RHGNN]:  Adds the 'device' parameter to the 'dataloader' object in the 'link_prediction.py' file to fix: "RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!" problem.

[RGCN] [RHGNN] Fixed code runtime error

---

openhgnn/dataset/NodeClassificationDataset.py

fix: [HAN] model "AttributeError: 'NoneType' object has no attribute 'items''' error using "acm_han_raw" dataset.

[Fix]: HAN model

---

openhgnn/config.ini

Due to our carelessness, the parameters were repeated when we modified the file, so we modified the error

[Fix] Fixed the configuration error of GIN

---

openhgnn/models/GIN.py

fix an error in GIN

---

openhgnn/output/GIE/README.md

add GIE README

---

openhgnn/output/GIN/README.md

ADD: add GIN README.md

---

openhgnn/config.ini
openhgnn/config.py
openhgnn/dataset/RecommendationDataset.py
openhgnn/dataset/__init__.py
openhgnn/dataset/academic_graph.py
openhgnn/experiment.py
openhgnn/models/DiffMG.py
openhgnn/models/__init__.py
openhgnn/trainerflow/DiffMG_trainer.py
openhgnn/trainerflow/__init__.py

[Model] Add DiffMG Model，created a new dataset for DiffMG called amazon

---

openhgnn/utils/visualize.py

add function `vis_emb` in `openhgnn/utils/visualize.py`

---

openhgnn/config.ini
openhgnn/config.py
openhgnn/models/GIN.py

Implemented the minibatch part of the GIN model. 
- Implemented updates to the minibatch part for the GIN model.
- Fixed issues with the previous minibatch part.
- Modified the config file to allow calling the GIN model using the minibatch method.

minibatch for GIN

---

docs/source/api/dataset.rst
docs/source/api/layer.rst
docs/source/api/model.rst
docs/source/api/task.rst
docs/source/api/trainerflow.rst

Docs modification

---

openhgnn/dataset/README.md
openhgnn/models/DMGI.py
openhgnn/models/HGT.py
openhgnn/models/HetSANN.py
openhgnn/models/SimpleHGN.py

Dataset&annotation test

---

openhgnn/config.py
openhgnn/models/HGAT.py
openhgnn/trainerflow/base_flow.py
openhgnn/trainerflow/link_prediction.py
openhgnn/trainerflow/node_classification.py

update some parameter parsing rules

update some parameter parsing rules

---

main.py
openhgnn/config.ini
openhgnn/config.py
openhgnn/trainerflow/kgcn_trainer.py
pytest.ini
tests/end2end/test_run.py

add end2end pytest [test_run.py] && rename kgcn --epoch_iter -> --max_epoch

add end2end pytest [test_run.py] && rename kgcn --epoch_iter -> --max_epoch

---

openhgnn/config.ini
openhgnn/config.py
openhgnn/dataset/RecommendationDataset.py
openhgnn/dataset/__init__.py
openhgnn/experiment.py
openhgnn/models/__init__.py
openhgnn/models/lightGCN.py
openhgnn/output/lightGCN/README.md
openhgnn/trainerflow/__init__.py
openhgnn/trainerflow/kgcn_trainer.py
openhgnn/trainerflow/lightGCN_trainer.py

add lightGCN model and modify KGCN model

---

openhgnn/config.ini
openhgnn/config.py
openhgnn/dataset/Ingram_dataset.py
openhgnn/dataset/__init__.py
openhgnn/experiment.py
openhgnn/models/Ingram.py
openhgnn/models/__init__.py
openhgnn/tasks/Ingram_task.py
openhgnn/tasks/__init__.py
openhgnn/trainerflow/Ingram_trainer.py
openhgnn/trainerflow/__init__.py
openhgnn/trainerflow/base_flow.py
openhgnn/utils/Ingram_utils.py

Ingram zzk

---

openhgnn/config.ini
openhgnn/config.py
openhgnn/dataset/LinkPredictionDataset.py
openhgnn/dataset/__init__.py
openhgnn/experiment.py
openhgnn/models/ExpressGNN.py
openhgnn/models/__init__.py
openhgnn/tasks/link_prediction.py
openhgnn/trainerflow/ExpressGNN_trainer.py
openhgnn/trainerflow/__init__.py
openhgnn/trainerflow/base_flow.py

Migrate ExpressGNN's source code into OpenHGNN.

Add ExpressGNN

---

main.py
openhgnn/experiment.py
openhgnn/trainerflow/base_flow.py
openhgnn/trainerflow/node_classification.py
openhgnn/utils/sampler.py

add distributed

---

main.py
openhgnn/dataset/NodeClassificationDataset.py
openhgnn/dataset/__init__.py
openhgnn/tasks/link_prediction.py
openhgnn/tasks/node_classification.py
openhgnn/trainerflow/link_prediction.py
openhgnn/trainerflow/node_classification.py

add GraphBolt

---

openhgnn/config.ini
openhgnn/config.py
openhgnn/models/NSHE.py

NSHE model

---

openhgnn/config.ini
openhgnn/config.py
openhgnn/dataset/MetaHIN_dataset.py
openhgnn/dataset/__init__.py
openhgnn/models/MetaHIN.py
openhgnn/models/__init__.py
openhgnn/tasks/__init__.py
openhgnn/tasks/coldstart_recommendation.py
openhgnn/trainerflow/__init__.py
openhgnn/trainerflow/base_flow.py
openhgnn/trainerflow/coldstart_recommendation.py
openhgnn/utils/evaluator.py

add MetaHIN model and dbook dataset

---

openhgnn/utils/README.md
openhgnn/utils/demo_experiment.py
openhgnn/utils/hgbi.py
openhgnn/utils/meta_path_analyse.py
openhgnn/utils/tsne_g.py

Merge code of Datasets and Interfaces for Benchmarking Heterogeneous Graph Neural Networks
Interfaces of Heterogeneous Graph Dataset
Toolkit for analyzing

add hgbi datasets&interfaces

---

openhgnn/dataset/NodeClassificationDataset.py
openhgnn/experiment.py

modify dataset path

---

openhgnn/experiment.py

modify dir path

---

CONTRIBUTING.md

Add Hai Huang to the list of advisors
